In [375]:
import pandas as pd

In [377]:
df = pd.read_csv(r"C:\Users\budar\Documents\GIT\Data cleaning_Cricket data\CricketTestMatchData.csv")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,HC Brook (ENG),2022-2024,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
14,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
16,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
17,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11
18,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7
19,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
20,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2
21,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
42,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84
44,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3
45,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
46,JE Root (ENG),2012-2024,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44
47,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
48,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
49,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
50,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0
51,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
52,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
55,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
56,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20
57,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1
58,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51,0
59,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [379]:
#rename the column names 

df = df.rename(columns = {'Mat': 'Matches','NO': 'Not_Out', 'HS': 'Highest_Inns_Score', 'BF': 'Balls_Faced', 'SR': 'Batting_Strike_Rate'})
df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,HC Brook (ENG),2022-2024,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
14,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
16,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
17,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11
18,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7
19,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
20,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2
21,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
42,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84
44,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3
45,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
46,JE Root (ENG),2012-2024,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44
47,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
48,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
49,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
50,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0
51,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
52,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
55,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
56,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20
57,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1
58,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51,0
59,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [381]:
df.head()

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,HC Brook (ENG),2022-2024,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [383]:
#check if there are any null values
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Out                False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced             True
Batting_Strike_Rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [385]:
df[df['Balls_Faced'].isna()==1]

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
17,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11

In [387]:
#Replacing the null values with 0

df['Balls_Faced'] = df['Balls_Faced'].fillna(0)

In [389]:
df['Batting_Strike_Rate'] = df['Batting_Strike_Rate'].fillna(0)

In [391]:
df[df['Player'] == 'CL Walcott (WI)']

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
17,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.0,15,14,1,107,11

In [393]:
df[df['Player'] == 'ED Weekes (WI)']

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258,2

In [395]:
#check for duplicates
df[df['Player'].duplicated()==1]

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
16,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [397]:
#check for number of duplicates 

df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'V Kohli (IND)'])]

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
16,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
54,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [399]:
#drop duplicates
df = df.drop_duplicates()

In [401]:
df[df['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'V Kohli (IND)'])]

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [403]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2015, 2016]
2     [2022, 2024]
3     [1963, 1970]
4     [1930, 1954]
6     [1924, 1935]
7     [1931, 1939]
8     [1955, 1968]
9     [1948, 1958]
10    [1927, 1947]
11    [1954, 1974]
13    [2000, 2015]
14    [2010, 2024]
15    [1908, 1930]
17    [1948, 1960]
18    [1937, 1955]
19    [1995, 2013]
20    [1921, 1929]
21    [2010, 2024]
22    [1968, 1973]
23    [1993, 1995]
24    [1970, 1984]
25    [1935, 1951]
26    [1989, 2013]
27    [1990, 2006]
28    [1976, 1993]
29    [1996, 2012]
30    [1998, 2010]
31    [2000, 2017]
32    [1995, 2012]
33    [1920, 1929]
34    [1992, 2002]
35    [2005, 2013]
36    [1994, 2015]
37    [1971, 1987]
38    [1985, 2004]
39    [1994, 2009]
40    [2004, 2018]
41    [1978, 1994]
42    [2019, 2024]
43    [1974, 1991]
44    [1937, 1957]
45    [1997, 2014]
46    [2012, 2024]
47    [1992, 2007]
48    [2018, 2024]
49    [1948, 1963]
50    [1911, 1928]
51    [2001, 2013]
52    [2019, 2021]
53    [2011, 2024]
55    [2004, 2015]
56    [1961, 1966]
57    [1929, 1949]
58    [1893, 1905]
59    [2001, 2013]
60    [1948, 1963]
61    [1965, 1981]
62    [2002, 2014]
63    [1924, 1934]
64    [1930, 1938]
65    [1928, 1934]
Name: Span, dtype: object

In [405]:
df['Span'].str.split(pat = '-').str[0]

0     1928
1     2015
2     2022
3     1963
4     1930
6     1924
7     1931
8     1955
9     1948
10    1927
11    1954
13    2000
14    2010
15    1908
17    1948
18    1937
19    1995
20    1921
21    2010
22    1968
23    1993
24    1970
25    1935
26    1989
27    1990
28    1976
29    1996
30    1998
31    2000
32    1995
33    1920
34    1992
35    2005
36    1994
37    1971
38    1985
39    1994
40    2004
41    1978
42    2019
43    1974
44    1937
45    1997
46    2012
47    1992
48    2018
49    1948
50    1911
51    2001
52    2019
53    2011
55    2004
56    1961
57    1929
58    1893
59    2001
60    1948
61    1965
62    2002
63    1924
64    1930
65    1928
Name: Span, dtype: object

In [407]:
df['First_Year'] = df['Span'].str.split(pat = '-').str[0]

C:\Users\budar\AppData\Local\Temp\ipykernel_19348\859380393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['First_Year'] = df['Span'].str.split(pat = '-').str[0]

In [409]:
df['Last_Year'] = df['Span'].str.split(pat = '-').str[1]

C:\Users\budar\AppData\Local\Temp\ipykernel_19348\1654888229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Last_Year'] = df['Span'].str.split(pat = '-').str[1]

In [411]:
df

,Player,Span,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,HC Brook (ENG),2022-2024,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968
9,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
14,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930
17,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960
18,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955
19,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
20,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929
21,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987
38,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
42,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991
44,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957
45,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
46,JE Root (ENG),2012-2024,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44,2012,2024
47,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
48,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
49,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963
50,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928
51,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
52,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
55,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
56,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966
57,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949
58,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51,0,1893,1905
59,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [413]:
#drop span column
df = df.drop(['Span'], axis = 1)

In [415]:
df

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,HC Brook (ENG),13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
6,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935
7,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939
8,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968
9,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958
10,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947
11,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974
13,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
14,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
15,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930
17,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960
18,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955
19,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
20,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929
21,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
22,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973
23,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
24,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
25,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951
26,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013
27,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
28,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993
29,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
30,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
31,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
32,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
33,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929
34,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
35,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
36,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
37,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987
38,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
39,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
40,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
41,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
42,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
43,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991
44,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957
45,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
46,JE Root (ENG),141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44,2012,2024
47,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
48,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
49,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963
50,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928
51,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
52,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
53,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
55,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
56,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966
57,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949
58,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,-,0.00,5,6,3,51,0,1893,1905
59,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
60,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963
61,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
62,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
63,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
64,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
65,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [219]:
df

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Starting_Year,First_Year
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1928
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2015
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2022
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1963
4,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1965
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2002
63,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1924
64,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1930
65,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1928

In [417]:
#split up the country from the player

df['Player'].str.split(pat = '(')

0             [DG Bradman , AUS)]
1               [AC Voges , AUS)]
2               [HC Brook , ENG)]
3              [RG Pollock , SA)]
4              [GA Headley , WI)]
6            [H Sutcliffe , ENG)]
7              [E Paynter , ENG)]
8          [KF Barrington , ENG)]
9               [ED Weekes , WI)]
10            [WR Hammond , ENG)]
11              [GS Sobers , WI)]
13          [KC Sangakkara , SL)]
14             [SPD Smith , AUS)]
15              [JB Hobbs , ENG)]
17             [CL Walcott , WI)]
18              [L Hutton , ENG)]
19          [JH Kallis , ICC/SA)]
20          [GE Tyldesley , ENG)]
21          [KS Williamson , NZ)]
22               [CA Davis , WI)]
23             [VG Kambli , IND)]
24           [GS Chappell , AUS)]
25              [AD Nourse , SA)]
26          [SR Tendulkar , IND)]
27            [BC Lara , ICC/WI)]
28         [Javed Miandad , PAK)]
29          [R Dravid , ICC/IND)]
30       [Mohammad Yousuf , PAK)]
31           [Younis Khan , PAK)]
32            [RT Ponting , AUS)]
33               [J Ryder , AUS)]
34              [A Flower , ZIM)]
35            [MEK Hussey , AUS)]
36          [S Chanderpaul , WI)]
37           [SM Gavaskar , IND)]
38              [SR Waugh , AUS)]
39             [ML Hayden , AUS)]
40         [AB de Villiers , SA)]
41             [AR Border , AUS)]
42            [DJ Mitchell , NZ)]
43           [IVA Richards , WI)]
44           [DCS Compton , ENG)]
45       [DPMD Jayawardene , SL)]
46               [JE Root , ENG)]
47    [Inzamam-ul-Haq , ICC/PAK)]
48         [M Labuschagne , AUS)]
49            [FMM Worrell , WI)]
50               [CP Mead , ENG)]
51          [V Sehwag , ICC/IND)]
52              [Abid Ali , PAK)]
53               [V Kohli , IND)]
55             [MJ Clarke , AUS)]
56               [KC Bland , SA)]
57             [B Mitchell , SA)]
58        [Hon.FS Jackson , ENG)]
59         [TT Samaraweera , SL)]
60             [RN Harvey , AUS)]
61            [KD Walters , AUS)]
62           [GC Smith , ICC/SA)]
63           [WH Ponsford , AUS)]
64             [SJ McCabe , AUS)]
65            [DR Jardine , ENG)]
Name: Player, dtype: object

In [419]:
df['Country'] = df['Player'].str.split(pat = '(').str[1]

In [421]:
df['Country'] = df['Country'].str.split(pat = ')').str[0]

In [423]:
df['Country']

0         AUS
1         AUS
2         ENG
3          SA
4          WI
6         ENG
7         ENG
8         ENG
9          WI
10        ENG
11         WI
13         SL
14        AUS
15        ENG
17         WI
18        ENG
19     ICC/SA
20        ENG
21         NZ
22         WI
23        IND
24        AUS
25         SA
26        IND
27     ICC/WI
28        PAK
29    ICC/IND
30        PAK
31        PAK
32        AUS
33        AUS
34        ZIM
35        AUS
36         WI
37        IND
38        AUS
39        AUS
40         SA
41        AUS
42         NZ
43         WI
44        ENG
45         SL
46        ENG
47    ICC/PAK
48        AUS
49         WI
50        ENG
51    ICC/IND
52        PAK
53        IND
55        AUS
56         SA
57         SA
58        ENG
59         SL
60        AUS
61        AUS
62     ICC/SA
63        AUS
64        AUS
65        ENG
Name: Country, dtype: object

In [425]:
df['Player'] = df['Player'].str.split(pat = '(').str[0]

In [427]:
df.head()

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024,ENG
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,WI

In [429]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
First_Year              object
Last_Year               object
Country                 object
dtype: object

In [431]:
df['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     334
1     269
2     186
3     274
4     270
6     194
7     243
8     256
9     207
10    336
11    365
13    319
14    239
15    211
17    220
18    364
19    224
20    122
21    251
22    183
23    227
24    247
25    231
26    248
27    400
28    280
29    270
30    223
31    313
32    257
33    201
34    232
35    195
36    203
37    236
38    200
39    380
40    278
41    205
42    190
43    291
44    278
45    374
46    254
47    329
48    215
49    261
50    182
51    319
52    215
53    254
55    329
56    144
57    189
58    144
59    231
60    205
61    250
62    277
63    266
64    232
65    127
Name: Highest_Inns_Score, dtype: object

In [433]:
# converting Highest_Inns_Score-- object datatype to int

df['Highest_Inns_Score'] = df['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [435]:
df['Highest_Inns_Score'].astype('int')

0     334
1     269
2     186
3     274
4     270
6     194
7     243
8     256
9     207
10    336
11    365
13    319
14    239
15    211
17    220
18    364
19    224
20    122
21    251
22    183
23    227
24    247
25    231
26    248
27    400
28    280
29    270
30    223
31    313
32    257
33    201
34    232
35    195
36    203
37    236
38    200
39    380
40    278
41    205
42    190
43    291
44    278
45    374
46    254
47    329
48    215
49    261
50    182
51    319
52    215
53    254
55    329
56    144
57    189
58    144
59    231
60    205
61    250
62    277
63    266
64    232
65    127
Name: Highest_Inns_Score, dtype: int32

In [437]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
First_Year              object
Last_Year               object
Country                 object
dtype: object

In [439]:
#Converting object data type to int [first year and last year]

df = df.astype({'First_Year': 'int', 'Last_Year': 'int'})

In [441]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
First_Year               int32
Last_Year                int32
Country                 object
dtype: object

In [443]:
df.head()

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024,ENG
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104,1,1930,1954,WI

In [445]:
df['Balls_Faced'] = df['Balls_Faced'].str.split(pat = '+').str[0]

In [447]:
df.isnull().any()

Player                 False
Matches                False
Inns                   False
Not_Out                False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced             True
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
First_Year             False
Last_Year              False
Country                False
dtype: bool

In [449]:
df[df['Balls_Faced'].isna() == 1]

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country
9,ED Weekes,48,81,5,4455,207,58.61,NaN,0.0,15,19,6,258,2,1948,1958,WI
17,CL Walcott,44,74,7,3798,220,56.68,NaN,0.0,15,14,1,107,11,1948,1960,WI

In [451]:
df['Balls_Faced'] = df['Balls_Faced'].fillna(0)

In [453]:
df[df['Balls_Faced'].isna() == 1]

Empty DataFrame
Columns: [Player, Matches, Inns, Not_Out, Runs, Highest_Inns_Score, Ave, Balls_Faced, Batting_Strike_Rate, 100, 50, 0, 4s, 6s, First_Year, Last_Year, Country]
Index: []

In [337]:
df['Balls_Faced'].astype('int')

0      9800
1      2667
2      1351
3      1707
4       416
6      6558
7      1288
8      4957
9         0
10     7491
11     4063
13    22882
14    18100
15     5363
17        0
18     2844
19    28903
20      178
21    17006
22      665
23     1823
24    13079
25      108
26    29437
27    19753
28    15164
29    31258
30    14372
31    19375
32    22782
33     2035
34    10636
35    12436
36    27395
37    14184
38    22461
39    14349
40    16077
41    27002
42     3014
43     9613
44     2731
45    22959
46    20876
47    16345
48     7809
49      488
50      619
51    10441
52     2445
53    15924
55    15456
57      158
59    11641
60     1799
61     8662
62    15525
63     3118
64     3217
65     2110
Name: Balls_Faced, dtype: int32

In [455]:
pd.set_option('display.max_rows', None)

In [457]:
df

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024,ENG
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
6,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG
7,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG
8,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG
9,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI
10,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI
13,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
14,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
15,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG
17,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI
18,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG
19,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
20,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG
21,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
22,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI
23,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
24,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
25,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA
26,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
41,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
42,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
43,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI
44,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG
45,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
46,JE Root,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44,2012,2024,ENG
47,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
48,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
49,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI
50,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG
51,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
52,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
53,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
55,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
56,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA
57,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA
58,Hon.FS Jackson,20,33,4,1415,144,48.79,-,0.00,5,6,3,51,0,1893,1905,ENG
59,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
60,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS
61,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [459]:
df = df.drop(56, axis = 0)

In [461]:
df = df.drop(58, axis = 0)

In [463]:
df

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024,ENG
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
6,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG
7,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG
8,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG
9,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI
10,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI
13,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
14,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
15,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG
17,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI
18,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG
19,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
20,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG
21,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ
22,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI
23,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
24,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
25,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA
26,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
33,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
37,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
41,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
42,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ
43,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI
44,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG
45,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
46,JE Root,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44,2012,2024,ENG
47,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
48,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
49,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI
50,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG
51,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
52,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
53,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND
55,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
57,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA
59,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
60,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS
61,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [465]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
First_Year               int32
Last_Year                int32
Country                 object
dtype: object

In [467]:
df['Balls_Faced'] = df['Balls_Faced'].astype('int')

In [469]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Out                  int64
Runs                     int64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced              int32
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
First_Year               int32
Last_Year                int32
Country                 object
dtype: object

In [473]:
#finding out career length

df['career_length'] = df['Last_Year'] - df['First_Year']

In [475]:
df['career_length']

0     20
1      1
2      2
3      7
4     24
6     11
7      8
8     13
9     10
10    20
11    20
13    15
14    14
15    22
17    12
18    18
19    18
20     8
21    14
22     5
23     2
24    14
25    16
26    24
27    16
28    17
29    16
30    12
31    17
32    17
33     9
34    10
35     8
36    21
37    16
38    19
39    15
40    14
41    16
42     5
43    17
44    20
45    17
46    12
47    15
48     6
49    15
50    17
51    12
52     2
53    13
55    11
57    20
59    12
60    15
61    16
62    12
63    10
64     8
65     6
Name: career_length, dtype: int32

In [477]:
df

,Player,Matches,Inns,Not_Out,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,First_Year,Last_Year,Country,career_length
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS,20
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
2,HC Brook,13,21,1,1231,186,61.55,1351,91.11,4,8,1,146,24,2022,2024,ENG,2
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI,24
6,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG,11
7,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG,8
8,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG,13
9,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI,10
10,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG,20
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI,20
13,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,15
14,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS,14
15,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG,22
17,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI,12
18,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG,18
19,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,18
20,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG,8
21,KS Williamson,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,NZ,14
22,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI,5
23,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,2
24,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS,14
25,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA,16
26,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND,24
27,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,16
28,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK,17
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,16
30,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,12
31,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,17
32,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,17
33,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS,9
34,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,10
35,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,8
36,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,21
37,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND,16
38,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,19
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,15
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,14
41,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS,16
42,DJ Mitchell,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,NZ,5
43,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI,17
44,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG,20
45,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL,17
46,JE Root,141,258,21,11804,254,49.80,20876,56.54,31,62,12,1287,44,2012,2024,ENG,12
47,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK,15
48,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS,6
49,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI,15
50,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG,17
51,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND,12
52,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK,2
53,V Kohli,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,2011,2024,IND,13
55,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS,11
57,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA,20
59,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL,12
60,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS,15
61,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS,16
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
63,WH Ponsford,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS,10
64,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS,8
65,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG,6

In [481]:
#Calculations with the data frame

#1.. Cricketers in this df what is the average career length 

df['career_length'].mean()

13.366666666666667

In [487]:
#2..Average Batting_strike_rate for cricketers who played over 10 years
df[df['career_length'] > 10] ['Batting_Strike_Rate'].mean()

49.06232558139534

In [497]:
#3.. find 3 cricketers who played before 1960

df[df['First_Year'] < 1960]['Player'].count()

22

In [499]:
#4..$ Max Highest Inns Scires by country

df.groupby('Country')['Highest_Inns_Score'].max().to_frame('HighInnCountry').reset_index().sort_values('HighInnCountry', ascending = False)

    Country HighInnCountry
5    ICC/WI            400
0       AUS            380
10       SL            374
11       WI            365
1       ENG            364
3   ICC/PAK            329
2   ICC/IND            319
8       PAK            313
9        SA            278
4    ICC/SA            277
6       IND            254
7        NZ            251
12      ZIM            232

In [501]:
#5.. 5 hundreds, fifties, ducks(0) avg by country

df.groupby('Country')[['100', '50', '0']].mean()

               100      50          0
Country
AUS      20.625000  28.375   8.562500
ENG      13.000000  22.250   4.416667
ICC/IND  29.500000  47.500  12.000000
ICC/PAK  25.000000  46.000  15.000000
ICC/SA   36.000000  48.000  13.500000
ICC/WI   34.000000  48.000  17.000000
IND      29.500000  36.500  10.750000
NZ       18.500000  22.000   6.000000
PAK      21.250000  28.000   9.500000
SA       11.500000  23.000   3.750000
SL       28.666667  44.000  12.333333
WI       16.625000  25.625   7.250000
ZIM      12.000000  27.000   5.000000